### ISSUE TITLE
Pull request bloqueado

### ISSUE THREAD

**Issue by greghonox** [kelvins/design-patterns-python#9]
Ola Kevins. Estou gostando de estudar pelo seu repositório. Já faz alguns meses que me interessei por design patterns. Estou tentando fazer um push mas não esta habilitado. Parabens pelo trabalho/estudos.

**Comment by kelvins** [comment]
Olá @greghonox, legal, obrigado. Para contribuir vc precisa fazer um fork, fazer suas alterações e depois submeter um pull request, aqui tem um tutorial de como fazer isso: 

https://imasters.com.br/desenvolvimento/como-contribuir-com-um-projeto-no-github

Qualquer dúvida é só falar
